version = 1

test_patterns = ["**/*.test.ts"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "docker"
