name: tasktix

services:
  web:
    build: .
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
