import type { Metadata } from 'next';
import { Providers } from './providers';
import { Button, Link, Navbar, NavbarBrand, NavbarContent, NavbarItem } from '@nextui-org/react';
import Snackbar from '@/components/snackbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body >
        <Providers>
          <Navbar maxWidth='xl'>
            <NavbarBrand as={Link} href="/">
              <p className="font-bold text-lg">TaskTactix</p>
            </NavbarBrand>
            <NavbarContent className='justify-center'>
              <NavbarItem>

              </NavbarItem>
            </NavbarContent>
            <NavbarContent justify='end'>
              <Button as={Link} color="primary" href="/login" variant="flat">
                Log In
              </Button>
            </NavbarContent>
          </Navbar>

          {children}
          
          <Snackbar />
        </Providers>
      </body>
    </html>
  );
}
